trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA


variables:
  - name: analysisProject
    value: OCS_DataRetrieval_PowerQuery

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, CommunityId, ClientId, ClientSecret, Resource'
        
      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
          workingDirectory: $(Build.SourcesDirectory)\ADHPowerQueryTest
          timeoutInMinutes: 3

  - job: Analysis
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)

    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'

      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build

      - template: '/miscellaneous/build_templates/binskim.yml@templates'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
