trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '/'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples


variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: projPath
    value: ''
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.ocs-data_retrieval-power_query_m.json
  - name: analysisProject
    value: OCS_DataRetrieval_PowerQuery

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)\OCSPowerQuery
        
      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(imageName)'
          workingDirectory: $(Build.SourcesDirectory)\OCSPowerQueryTest

  - job: Analysis
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)

    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build

      - template: '/miscellaneous/build_templates/binskim.yml@templates'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'